### ISSUE TITLE
Update Stannp response `id` from string to int

### ISSUE THREAD

**Issue by z-cran** [CopilotIQ/stannp-client-golang#4]
Stannp recently changed their `id` from a `string` to `int`, causing unmarshalling issues.
```json
{
  "success": true,
  "data": {
    "pdf": "long-url",
    "id": 0,
    "created": "2023-06-16 14:27:01",
    "format": "US-LETTER",
    "cost": "0.81",
    "status": "test"
  }
}
```

**Comment by dillonstreator** [comment]
Looks like #5 was already merged but thoughts on creating a type which can json unmarshal into either an `int` or a `string` to be a bit more defensive? @z-cran @seantcanavan

**Comment by z-cran** [comment]
> Looks like #5 was already merged but thoughts on creating a type which can json unmarshal into either an `int` or a `string` to be a bit more defensive? @z-cran @seantcanavan

That'd be a safer approach for sure.

**Comment by seantcanavan** [comment]
#6 should close this out - thanks @dillonstreator
